### ISSUE TITLE
Individual type of results in the report should be togglable

### ISSUE THREAD

**Issue by siteshwar** [csutils/csmock#177]
This is a follow up on [fedora-devel discussion](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/KFAJTP3RZFZHVTAZBJ22Z4TYWYMPDTBB/).

There is a suggestion make the individual type of results togglable to make the reports easier to read. This issue tracks implementing this feature in `csmock`.

**Comment by kdudka** [comment]
The HTML output is generated by https://github.com/csutils/csdiff/blob/main/src/lib/writer-html.cc I think it can be extended to optionally embed some interactive features into the HTML page but doing it in a way that users would find sufficiently intuitive and useful is a though task.  Another option would be to convert the scan results into SARIF (which `csdiff` supports already) and use an existing tool designed for presenting scan results to avoid reinventing the wheel.

**Comment by siteshwar** [comment]
I have opened an issue on the [csdiff](https://github.com/csutils/csdiff/issues/194) repository to follow up on it.

**Comment by lzaoral** [comment]
> I have opened an issue on the https://github.com/csutils/csdiff/issues/194 repository to follow up on it.

@siteshwar Nothing major but you can easily transfer issues between repos in the same org using the `Transfer issue` button. 😄
