### ISSUE TITLE
Implement capture of sanitizer reports

### ISSUE THREAD

**Issue by lzaoral** [csutils/csmock#78]
* [x] Compile with `-g` and `-fno-omit-frame-pointer` to always get proper debug information.
* [x] Use `UBSAN_OPTIONS=print_stacktrace=1` to get proper stack traces. Otherwise, only the initial line is shown.
* [x] Use `${SANITIZER}_OPTIONS=log_path=${path}/${name}` to produce `${path}/${name}.$$` files with `${SANITIZER}` reports.
* [ ] Add support for memory sanitizer.

**Comment by lzaoral** [comment]
ASAN and UBSAN log capture cannot be combined: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94328

**Comment by kdudka** [comment]
There might be more options conflicting with each other.  Some of the combinations seem to be avoided in the current experimental implementation: https://github.com/csutils/csmock/blob/7bdf0ff4668f2f77d53eeb791694dea2b2cc9871/py/plugins/gcc.py#L90

**Comment by lzaoral** [comment]
FYI: MSAN is not compatible with GCC, so I'm not going to focus on its support at the moment.
